Add semantic versioning input limit.

diff --git a/.github/workflows/create_release_pr.yml b/.github/workflows/create_release_pr.yml
--- a/.github/workflows/create_release_pr.yml
+++ b/.github/workflows/create_release_pr.yml
@@ -17,10 +17,24 @@ jobs:
         env: 
           VERSION_INPUT: ${{ github.event.inputs.versionName }}
         run: |
-          # Ref: https://github.com/orgs/community/discussions/48373#discussioncomment-7543209                                                                                                 
           # Ref: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string                                                                                    
+          SEMVER_REGEX='^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
+
+          # Ref: https://stackoverflow.com/a/17368090
+          MAX_VERSION_INPUT_SIZE=255
+          echo "Validating length of version name is less than ${MAX_VERSION_INPUT_SIZE} characters..."                                                                                                     
+          if [ ${#VERSION_INPUT} -gt $MAX_VERSION_INPUT_SIZE ]; then
+            echo "Version name "${VERSION_INPUT}" too long."
+            exit 1
+          fi
+
+          # Ref: https://github.com/orgs/community/discussions/48373#discussioncomment-7543209                                                                                                 
           echo "Validating version name to make sure it adheres to semantic versioning..."                                                                                                     
-          echo "$VERSION_INPUT" | grep -P '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'     
+          if ! "$VERSION_INPUT" | grep -P "${SEMVER_REGEX}"; then
+            echo "Version name "${VERSION_INPUT}" invalid."
+            exit 2
+          fi
+
       - name: Checkout Repository
         uses: actions/checkout@v5
         with:
