Validate release version parameter and enforce 1.x as the target branch.

diff --git a/.github/workflows/release_1.x.yml b/.github/workflows/release_1.x.yml
--- a/.github/workflows/release_1.x.yml
+++ b/.github/workflows/release_1.x.yml
@@ -1,10 +1,13 @@
 name: Release 1.x
+
 on:
   workflow_dispatch:
     inputs:
-      version:
-        description: '1.x version to release'
+      versionName:
+        description: '1.x version to release (e.g., 1.1.0)'
         required: true
+        type: string
+
 env:
   SIGNING_KEY_FILE_PATH: /home/runner/secretKey.gpg
 jobs:
@@ -13,6 +16,31 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     steps:
+      - name: Validate Version Name
+        env:
+          VERSION_NAME: ${{ github.event.inputs.versionName }}
+        run: |
+          # Ref: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string                                                                                    
+          SEMVER_REGEX='^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
+
+          # Ref: https://stackoverflow.com/a/17368090
+          MAX_VERSION_INPUT_SIZE=255
+          echo "Validating length of version name is less than ${MAX_VERSION_INPUT_SIZE} characters..."                                                                                                     
+          if [ ${#VERSION_NAME} -gt $MAX_VERSION_INPUT_SIZE ]; then
+            echo "Version name "${VERSION_NAME}" too long."
+            exit 1
+          fi
+
+          # Ref: https://github.com/orgs/community/discussions/48373#discussioncomment-7543209                                                                                                 
+          echo "Validating version name to make sure it adheres to semantic versioning..."                                                                                                     
+          if ! echo "$VERSION_NAME" | grep -P "${SEMVER_REGEX}"; then
+            echo "Version name "${VERSION_NAME}" invalid."
+            exit 2
+          fi
+
+          # append validated version input to action runner environment
+          # Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-writing-an-environment-variable-to-github_env
+          echo "VALIDATED_VERSION_NAME=${VERSION_NAME}" >> "$GITHUB_ENV"
       - name: Checkout Repository
         uses: actions/checkout@v4
       - name: Set up Java
@@ -124,6 +152,7 @@ jobs:
     needs: [ unit_test_finished, build_aar ]
     name: Publish All Modules To Sonatype
     runs-on: ubuntu-latest
+    if: ${{ github.ref == 'refs/heads/1.x' }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -139,7 +168,7 @@ jobs:
           signing_file_path: ${{ env.SIGNING_KEY_FILE_PATH }}
       - name: Update Version
         run: |
-          ./gradlew -PversionParam=${{ github.event.inputs.version }} changeReleaseVersion
+          ./gradlew -PversionParam="${VALIDATED_VERSION_NAME}" changeReleaseVersion
       - name: Publish All Modules
         uses: ./.github/actions/publish_all_modules
         with:
@@ -167,17 +196,17 @@ jobs:
       - name: Update Version
         run: |
 
-          ./gradlew -PversionParam=${{ github.event.inputs.version }} updateCHANGELOGVersion
-          ./gradlew -PversionParam=${{ github.event.inputs.version }} changeReleaseVersion
+          ./gradlew -PversionParam="${VALIDATED_VERSION_NAME}" updateCHANGELOGVersion
+          ./gradlew -PversionParam="${VALIDATED_VERSION_NAME}" changeReleaseVersion
 
           git add .
-          git commit -m 'Bump version to ${{ github.event.inputs.version }}'
-          git tag ${{ github.event.inputs.version }} -a -m 'Release ${{ github.event.inputs.version }}, by ${{ github.actor }}'
+          git commit -m "Bump version to ${VALIDATED_VERSION_NAME}"
+          git tag "${VALIDATED_VERSION_NAME}" -a -m "Release ${VALIDATED_VERSION_NAME}, by ${{ github.actor }}"
 
           ./gradlew incrementSnapshotVersion
           git add .
           git commit -m 'Next version ready'
-          git push origin HEAD ${{ github.event.inputs.version }}
+          git push origin HEAD "${VALIDATED_VERSION_NAME}"
       - name: Save changelog entries to a file
         run: sed -e '1,/##/d' -e '/##/,$d' CHANGELOG.md > changelog_entries.md
       - name: Create GitHub release
@@ -186,8 +215,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ github.event.inputs.version }}
-          release_name: ${{ github.event.inputs.version }}
+          tag_name: ${{ env.VALIDATED_VERSION_NAME }}
+          release_name: ${{ env.VALIDATED_VERSION_NAME }}
           body_path: changelog_entries.md
           draft: false
           prerelease: false
